---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate --production

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:12
    commands:
      - npm test

  # No tests
  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-user-tools
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

---
kind: secret
name: docker_username
data: vBa1cv8GcOWs1yZJKm8GlxEjIapUzl5x6r5MbvXtX2Xz8XqSZx/mzIlypxMuJvTbj0k=
---
kind: secret
name: docker_password
data: vaweoJ+uhxZuUgs/OrEqaClKst9ox8CCP68tOvgTeUKVnY/EsatL26tr+Kj3zihc91rCFGUyUfvKAmYZhsVBp4E/C6dHZehjGYSPYg6rvsywiK+aCmKUhzMPI0MDeNsDC1FK440c6Gi27LDWuo8/4W8Umu8JEfYBsB1R3rgiSKaGtN6bSUTPc6u+x9QjCuAdgcaCtIxG5+Rkfadx0/d5AmUHnpwxsom5d29s1sDeFqaca+B+QkLoe66zhl2EIeCknE8ejvR1g1lRALjYf8i9gIxTr9jACMTI4NOxZoa/oJl5ljw2GGxkx7M7TRtNy4bYwFlwRNKsYas3Y6PDHY+diFm4D72pLhpv
---
kind: signature
hmac: 3f521c419abd4967960229406136c507095b73c9ea2b8200ee75f4e7f0aa21ee

...
