---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate --production

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:12
    commands:
      - npm test

  # No tests
  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist
---
kind: signature
hmac: 72aa323fa70ef2a16b7c409b7d3415a4fcd43a0eba32708e06542681a0af916b

...
